spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xx?useUnicode=yes&characterEncode=UTF-8&useSSL=true
    username: root
    password: root
  session:
    store-type: none
# 配置返回时json中将Date转为时间戳
  jackson:
    serialization:
      write-dates-as-timestamps: true
  security:
    user:
      name: root
      password: root
