spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/paascloud_uac?useUnicode=yes&characterEncode=UTF-8&useSSL=true
    username: root
    password: root
  session:
    store-type: REDIS
# 配置返回时json中将Date转为时间戳
  jackson:
    serialization:
      write-dates-as-timestamps: true
  redis:
    host: 192.168.25.131
    password: corner666
    port: 6379
corner:
  security:
    browser:
#      loginPage: /demo-sign.html
#      loginType: REDIRECT
#      loginType: JSON
      signUpUrl: /demo-signUp.html
      signOutUrl: /demo-logout.html
    code:
      imageCode:
#        length: 5
#        width: 100
        url: /authentication/form
      smsCode:
        url: /authentication/mobile
    social:
#      filterProcessesUrl: /login/callback
      filterProcessesUrl: /qqLogin
      qq:
        app-id: 101503943
        app-secret: ea51ad9f67d1244537f4f2ed9db9242c
        providerId: qq
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
        providerId: weixin
server:
  port: 8080
  servlet:
    session:
      # 必须大于1分钟
      timeout: 1200
security:
  oauth2:
    client:
      client-id: corner
      client-secret: aaa
      registered-redirect-uri: "http://example.com"
