
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xx?useUnicode=yes&characterEncode=UTF-8&useSSL=true
    username: root
    password: root
  session:
    store-type: none
# 配置返回时json中将Date转为时间戳
  jackson:
    serialization:
      write-dates-as-timestamps: true
corner:
  security:
    browser:
#      loginPage: /demo-sign.html
#      loginType: REDIRECT
#      loginType: JSON
      signUpUrl: /demo-signUp.html
    code:
      imageCode:
#        length: 5
#        width: 100
        url: /authentication/form,/user,/user/*
      smsCode:
        url: /authentication/mobile
    social:
      filterProcessesUrl: /login/callback
      qq:
        app-id: 101503943
        app-secret: ea51ad9f67d1244537f4f2ed9db9242c
        providerId: qq
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
        providerId: weixin
server:
  port: 80
