
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xx?useUnicode=yes&characterEncode=UTF-8&useSSL=true
    username: root
    password: root
  session:
    store-type: none
# 配置返回时json中将Date转为时间戳
  jackson:
    serialization:
      write-dates-as-timestamps: true
corner:
  security:
#    browser:
#      loginPage: /demo-sign.html
#      loginType: REDIRECT
#      loginType: JSON
    code:
      imageCode:
#        length: 5
#        width: 100
        url: /authentication/form,/user,/user/*
      smsCode:
        url: /authentication/mobile
    social:
      filterProcessUrl: /auth/callback
      qq:
        app-id: 101431061
        app-secret: 0154c848f45fc705412462d4f99a592c
        providerId: qq
